# Very much possible tab completion
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
bind 'C-y:yes'

shopt -s histappend
shopt -s autocd

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Clean-up, clean up, everybody everywhere!
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Bash History
HISTSIZE=100
HISTFILESIZE=200
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/bash/history"

alias ls="ls --color=auto"
alias tms="tmux new -d -s hack && sleep 0.1s && tmux new -d -s notes -c ~/notes/ && tmux new -d -s util && tmux attach"
alias tma="tmux attach"

# enable programmable completion features 
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

source ~/.config/lf/lf.bash

PS1="\[\033[1;37m\]\w $ \[\033[00m\]" # Setting PS1 to show full path
export PROMPT_DIRTRIM=3 # Trimming path to 4 directories

# if running bash - THIS CAUSES THE ERROR OF PS1 NOT LOADING!!
#if [ -n "$BASH_VERSION" ]; then
#    # include .bashrc if it exists
#    if [ -f "$HOME/.bashrc" ]; then
#    . "$HOME/.bashrc"
#    fi
#fi

# Pomodoro shell script here: https://github.com/rukshn/pomodoro?tab=readme-ov-file
